### ISSUE TITLE
b3 sources: should we keep appendix A (tutorial)

### ISSUE THREAD

**Issue by tgingold-cern** [fossi-foundation/wishbone#5]
Should we keep the tutorial appendix ?  It is not part of the specifications, has a lot of drawings...

**Comment by wallento** [comment]
Hi, I tend to say no. I don't see that much value, plus its an appendix. Let's keep it as an optional todo-item, I think. Cheers, Stefan

**Comment by tgingold-cern** [comment]
I agree.
